set SynModuleInfo {
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_4 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_4 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_58_4
    SUBMODULES {
      {MODELNAME extendedKalmanFilter_sparsemux_9_2_64_1_1 RTLNAME extendedKalmanFilter_sparsemux_9_2_64_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME extendedKalmanFilter_flow_control_loop_pipe_sequential_init RTLNAME extendedKalmanFilter_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME extendedKalmanFilter_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_41 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_41 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_58_41}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_42 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_42 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_58_42}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_43 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_58_43 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_58_43}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_7 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_7 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_67_7
    SUBMODULES {
      {MODELNAME extendedKalmanFilter_mux_4_2_64_1_1 RTLNAME extendedKalmanFilter_mux_4_2_64_1_1 BINDTYPE op TYPE mux IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_74 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_74 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_67_74}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_75 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_75 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_67_75}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_76 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_67_76 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_67_76}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_94_12 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_94_12 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_94_12}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_94_127 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_94_127 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_94_127}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_101_14 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_101_14 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_101_14}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_101_148 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_101_148 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_101_148}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_110_17 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_110_17 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_110_17}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_110_179 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_110_179 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_110_179}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_20 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_20 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_121_20}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2010 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2010 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2010}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2011 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2011 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2011}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2012 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2012 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_121_2012}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_128_22 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_128_22 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_128_22
    SUBMODULES {
      {MODELNAME extendedKalmanFilter_ddiv_64ns_64ns_64_59_no_dsp_1 RTLNAME extendedKalmanFilter_ddiv_64ns_64ns_64_59_no_dsp_1 BINDTYPE op TYPE ddiv IMPL fabric LATENCY 58 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_135_24 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_135_24 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_135_24}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_140_25_VITIS_LOOP_141_26 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_140_25_VITIS_LOOP_141_26 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_140_25_VITIS_LOOP_141_26}
  {SRCNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_148_28_VITIS_LOOP_149_29 MODELNAME extendedKalmanFilter_Pipeline_VITIS_LOOP_148_28_VITIS_LOOP_149_29 RTLNAME extendedKalmanFilter_extendedKalmanFilter_Pipeline_VITIS_LOOP_148_28_VITIS_LOOP_149_29}
  {SRCNAME extendedKalmanFilter MODELNAME extendedKalmanFilter RTLNAME extendedKalmanFilter IS_TOP 1
    SUBMODULES {
      {MODELNAME extendedKalmanFilter_dsub_64ns_64ns_64_13_full_dsp_1 RTLNAME extendedKalmanFilter_dsub_64ns_64ns_64_13_full_dsp_1 BINDTYPE op TYPE dsub IMPL fulldsp LATENCY 12 ALLOW_PRAGMA 1}
      {MODELNAME extendedKalmanFilter_dadd_64ns_64ns_64_13_full_dsp_1 RTLNAME extendedKalmanFilter_dadd_64ns_64ns_64_13_full_dsp_1 BINDTYPE op TYPE dadd IMPL fulldsp LATENCY 12 ALLOW_PRAGMA 1}
      {MODELNAME extendedKalmanFilter_dmul_64ns_64ns_64_15_max_dsp_1 RTLNAME extendedKalmanFilter_dmul_64ns_64ns_64_15_max_dsp_1 BINDTYPE op TYPE dmul IMPL maxdsp LATENCY 14 ALLOW_PRAGMA 1}
      {MODELNAME extendedKalmanFilter_dadddsub_64ns_64ns_64_13_full_dsp_1 RTLNAME extendedKalmanFilter_dadddsub_64ns_64ns_64_13_full_dsp_1 BINDTYPE op TYPE dadd IMPL fulldsp LATENCY 12 ALLOW_PRAGMA 1}
      {MODELNAME extendedKalmanFilter_temp2_RAM_AUTO_1R1W RTLNAME extendedKalmanFilter_temp2_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
